print('Media ponderada de provas de um aluno')
Peso1 = float(input('Digite o peso da prova 1: '))
Nota1 = int(input('Digite a nota da prova 1: '))
Peso2 = float(input('Digite o peso da prova 2: '))
Nota2 = int(input('Digite a nota da prova 2: '))
MediaPon = ((Peso1 * Nota1) + (Peso2 * Nota2)) / (Peso1 + Peso2)
print('A media ponderada é: ', MediaPon)
print('Fim do programa')
input('Enter para sair')
